services:
  mongo-db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}